### ISSUE TITLE
Scroll Position

### ISSUE THREAD

**Issue by misticini** [imanhodjaev/ember-perfect-scroll#1]
Hello,

It's possible put the scroll on  the bottom, by default on the page load?

Regards

**Comment by imanhodjaev** [comment]
@misticini I'm not sure I understand you, can you please illustrate or explain what do you mean.
I am planning to rewrite this project to match ember addon structure

**Comment by misticini** [comment]
Hello,

thank u for your answer :) 

I'm talking about property scrollTop listed here: https://github.com/noraesae/perfect-scrollbar

Regards

**Comment by imanhodjaev** [comment]
@misticini I made [some refactoring](https://github.com/imanhodjaev/ember-perfect-scroll/blob/master/addon/components/perfect-scroll.js) and version update, also added `scrollTop` options though it seems this option is not respected by `perfect-scrollbar`

**Comment by imanhodjaev** [comment]
So I close this issue, because this feature was not requested by other people though added `scrollTop` and `scrollLeft` options.
