### ISSUE TITLE
Some Ember actions not working

### ISSUE THREAD

**Issue by DaveFerBear** [imanhodjaev/ember-perfect-scroll#10]
I have wrapped my component template in the perfect-scroll wrapper, and am having some success with triggering actions, but I cannot get some of the actions specified in the docs are not working.

```
{{#perfect-scroll ps-scroll-down=(action 'scrolledDown')}}
	{{#each model as |slide|}}
		{{#if (ifEq slide.type "quote")}}
			{{slide-quote image=slide.bgImage color=slide.bgColor quote=slide.quote person=slide.person height=slide.height}}
		{{/if}}
		{{#if (ifEq slide.type "twitter")}}
			{{slide-twitter}}
		{{/if}}
	{{/each}}
{{/perfect-scroll}}
{{outlet}}
```

```
import Ember from 'ember';

export default Ember.Controller.extend({
	actions: {
		scrolledDown: function() {
			console.log('down');
		}
	}
});
```

The `ps-scroll-y`is triggered on any type of scrolling (even in x), however `ps-scroll-up` and `ps-scroll-down` are not working.

**Comment by imanhodjaev** [comment]
@DaveFerBear thank you I will look into it.

**Comment by DaveFerBear** [comment]
@imanhodjaev any update on this?

**Comment by imanhodjaev** [comment]
@DaveFerBear I was unable to reproduce the issue you described. Scrolling down always triggered in my case. I tried scrolling down by mouse and use down arrow too and it works.

```hbs
{{#perfect-scroll scrollTop=50 ps-scroll-down=(action 'scrollDown')}}
FOO FOO
{{/perfect-scroll}}
```

Screen
![demo](https://cloud.githubusercontent.com/assets/354868/18888382/5e449742-84f8-11e6-9030-a3ff288a9177.gif)
