### ISSUE TITLE
Upgrade addon once Ember 2.12 released

### ISSUE THREAD

**Issue by imanhodjaev** [imanhodjaev/ember-perfect-scroll#12]
Once Ember 2.12 will be released I will upgrade addon to the latest version of Emebr-cli.

**Comment by ludalex** [comment]
What about import `perfect-scrollbar` from the npm package instead of bower? 
The trend is to completely remove bower usage.

**Comment by imanhodjaev** [comment]
@ludalex yes I will make this change to import `perfect-scrollbar` from `node_modules`.
