### ISSUE TITLE
Import perfect-scrollbar from node_modules instead of bower_components

### ISSUE THREAD

**Issue by imanhodjaev** [imanhodjaev/ember-perfect-scroll#15]
As @ludalex noted that it will be good to import perfect-scrollbar from the npm package instead of bower and `ember-cli` is also moving away from bower, this issue should be addressed.

**Comment by feanor07** [comment]
now that my pr is merged; how about getting a new tag, publishing it and closing this issue? I can be a maintainer as I already indicated in another issue if you like :)

**Comment by imanhodjaev** [comment]
@feanor07 good point! By the way I aded you as a maintainer.
