### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by imanhodjaev** [imanhodjaev/ember-perfect-scroll#18]
Hi All,

It would be nice for me to find maintainer for this small project.

Thanks.

**Comment by feanor07** [comment]
i have created a pull request and i will be happy to be a maintainer if you accept. I am actively using ember at work and I hope to use this add-on since IMHO, contextual component usage like this is a good way to go.

**Comment by imanhodjaev** [comment]
@feanor07 I just added you in maintainers list, thanks for supporting. I will tag a new version today.

**Comment by feanor07** [comment]
@imanhodjaev that is great; thx.

**Comment by imanhodjaev** [comment]
@feanor07 ✨🍰✨
