### ISSUE TITLE
FYI on Install

### ISSUE THREAD

**Issue by joshuairl** [imanhodjaev/ember-perfect-scroll#2]
Path or pattern "bower_components/perfect-scrollbar/src/perfect-scrollbar.js" did not match any files
Looks like it's final resting place is now at:
`bower_components/perfect-scrollbar/js/perfect-scrollbar.js`

Just figured I'd let you know.  I could do a pull request if you want.

**Comment by joshuairl** [comment]
Oh, it looks like your git repo is up to date but maybe it needs NPM updated so it gets the latest release?
Sorry for the issue.

**Comment by t4t5** [comment]
Indeed, NPM still needs to be updated. I had the same issue. :)

**Comment by imanhodjaev** [comment]
@joshuairl @t4t5 sorry guys I will publish update to npm

**Comment by imanhodjaev** [comment]
I'm having busy weeks doing my main job

**Comment by imanhodjaev** [comment]
If you want to help and contribute you are welcome

**Comment by t4t5** [comment]
Oh, no worries, it was a simple fix. :) Thanks for the library, I'm trying it out right now. If I find something else, I'll make a pull request!
