### ISSUE TITLE
Draft release notes

### ISSUE THREAD

**Issue by imanhodjaev** [imanhodjaev/ember-perfect-scroll#24]
Hi @feanor07,
Thanks for contributions I quite happy with them, can you please draft release notes, name it as you want and update releases?

I published changes for 0.1.17 ✨🍰✨.

Thanks.

**Comment by feanor07** [comment]
Thx @imanhodjaev for the reminder; I guess I've nailed it :)

**Comment by imanhodjaev** [comment]
Nice :sparkles::rocket::sparkles::star2: thanks @feanor07
