### ISSUE TITLE
updating perfect-scrollbar

### ISSUE THREAD

**Issue by feanor07** [imanhodjaev/ember-perfect-scroll#25]
We have been using [perfect-scrollbar](https://github.com/utatti/perfect-scrollbar/releases)'s version 0.8.1. It should be nice if we can update to the latest version; that is v1.1.0 as of 25/10/2017.

**Comment by feanor07** [comment]
i had already opened an issue that prevented us from testing our code in newer versions:
https://github.com/utatti/perfect-scrollbar/issues/712

after that fix; i finally managed to update our code to latest version v1.3.0 as of 04/12/2017.

**Comment by feanor07** [comment]
finished the update and proposed a new tag. waiting for merge.

**Comment by sultaniman** [comment]
📦 Merged and published! Nice job @feanor07 ✨🍰✨
