### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by BenjaminHorn** [imanhodjaev/ember-perfect-scroll#4]
I try to install this addon on:
- ember: 2.1.0
- ember-cli: 1.13.8

After `npm install --save-dev ember-perfectscroll` I try to run `ember g perfect-scroll` but I'm getting the following error:

*version: 1.13.8
installing perfect-scroll
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.*

I can see **ember-perfectscroll** in the *node_modules* directory, but it looks like the **perfect-scrollbar** bower module is not installed.

If I try to run `ember serve` 

*ENOENT, no such file or directory '/home/my/projects/my-project/tmp/concat_with_maps-input_base_path-k7weDUl2.tmp/0/bower_components/perfect-scrollbar/js/perfect-scrollbar.js'*

**Comment by imanhodjaev** [comment]
@BenjaminHorn thank you very much for reporting this issue I will fix it in 1-2 days

**Comment by ancashoria** [comment]
Hey @imanhodjaev any news about this ?
Thanks

**Comment by imanhodjaev** [comment]
@ancashoria @BenjaminHorn sorry for late update, can you please check again I just updates perfect-scrollbar version, also tried to run dummy application to test scrollbars and it worked for me. 
Also in case if the same error occurs please install `perfect-scrollbar` manually this should fix problem

`bower install perfect-scrollbar` and please report back if possible.

**Comment by BenjaminHorn** [comment]
@imanhodjaev  thanks, it worked with manually installing bower dependency. **ember g perfect-scroll** still fails.

**Comment by fpauser** [comment]
#6 should fix this.

**Comment by imanhodjaev** [comment]
@BenjaminHorn @ancashoria this issue is fixed now, big thanks to @fpauser
