### ISSUE TITLE
Rename blueprint to ember-perfect-scroll

### ISSUE THREAD

**Issue by simonihmig** [imanhodjaev/ember-perfect-scroll#8]
The default way of installing addons with ember-cli is `ember install <addonname>`.
This installs the addon from npm, and executes the <addonname> blueprint if available (to install bower deps for example).

The second step does not work with ember-perfect-scroll, because you have named the bluebrint "perfect-scroll" instead of "ember-perfect-scroll". Renaming it should be all, so `ember install ember-perfect-scroll` should work then as expected!

**Comment by imanhodjaev** [comment]
@simonihmig can you please make related changes and make PR once it works I will merge?

Thank you.

**Comment by imanhodjaev** [comment]
@simonihmig done.
